### PR TITLE
Testing yo

### PR DESCRIPTION
**Pull request by omdnrd**
Lemme merge bro

### CODE REVIEW

**Comment by omdnrd** [comment]
So I noticed you're not having to stringify JSON or anything from the frontend. Why is that? and also how would I go about adding a delete function to the income, expense, and family pages?

**Comment by cuddyz** [comment]
> So I noticed you're not having to stringify JSON or anything from the frontend.

This is actually handled by the `HttpClient` in the web-request.service.ts.  This HttpClient actually handles all the parsing and stringifying so you just need to pass it the JS object and it does the rest.

> how would I go about adding a delete function to the income, expense, and family pages?

I'll throw up and example PR on the Income page and you can follow that as a model for the rest of the pages if that is cool.  The app needs a few changes for it to support deleting.

**Comment by omdnrd** [comment]
Oh for sure I'll just be able to duplicate it from there. I'm sorry if I'm badgering you too man. You're probably at work rn. It's just like you're a lifeline for us so I"m tryna do as much as I can. As you can probably tell from my shitty code I'm still very new to angular.

**Comment by cuddyz** [comment]
> You're probably at work rn

No worries Tuesday is my "meetings" day so I am just working while listening so no stress.

> It's just like you're a lifeline for us so I"m tryna do as much as I can.

I've been exactly where you are and know how it feels.  I'm just glad I am able to help!

> As you can probably tell from my shitty code

We all start somewhere, it may seem like I am just flying through this but I've been a web developer for 8 years now and do this every single day of my life.  I started at UMSL just like you and was writing code just like this.  You have built some great stuff here it just needed a bit of tinkering 😇

**Comment by omdnrd** [comment]
I really appreciate that man, and everything you’re doing for us. Hopefully
I can pass this onto the next struggling programmer like myself. I think I
may have just messed up on the code copying here but I’m getting an error
on the delete function, I’ll push my test branch rn so you can see what’s
causing it.

**Comment by cuddyz** [comment]
Hmm let know your branch name and I'll take a look.

Locally I am running:
Frontend -> `main` branch
Backend -> `yemi` branch

with no local changes and not seeing any errrors.

**Comment by cuddyz** [comment]
Oh wait there is a bug on `main` when you create a record and then delete because there isn't an id.  Once sec I'll get a fix up.

**Comment by omdnrd** [comment]
Frontend I am on the test branch. The original plan was for me to be
working on the main and everyone else would be on their branches but that
would put main ahead and create merge conflicts right? I’ve been using test.

**Pull request merged**
